site_name: Keystone API
nav:
  - Introduction: index.md
  - Installation:
      - install/slurm.md
      - install/docker.md
      - install/python.md
      - install/settings.md
  - REST API:
    - API Specification: api/index.html
    - api/authentication.md
    - api/filtering.md
  - Developer Notes:
      - Common Tasks: developer/common.md
